// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 45.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'commmercial_directory_seller';

  static const String assets_home_bottom_icons_fav_svg = 'assets/home_bottom_icons/fav.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_fav_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/fav.svg';

  static const String assets_home_bottom_icons_favorite_active_svg = 'assets/home_bottom_icons/favorite_active.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_favorite_active_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/favorite_active.svg';

  static const String assets_home_bottom_icons_home_svg = 'assets/home_bottom_icons/home.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_home_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/home.svg';

  static const String assets_home_bottom_icons_home_active_svg = 'assets/home_bottom_icons/home_active.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_home_active_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/home_active.svg';

  static const String assets_home_bottom_icons_sectore_svg = 'assets/home_bottom_icons/sectore.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_sectore_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/sectore.svg';

  static const String assets_home_bottom_icons_sectore_active_svg = 'assets/home_bottom_icons/sectore_active.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_sectore_active_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/sectore_active.svg';

  static const String assets_home_bottom_icons_user_svg = 'assets/home_bottom_icons/user.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_user_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/user.svg';

  static const String assets_home_bottom_icons_user_active_svg = 'assets/home_bottom_icons/user_active.svg';
  static const String commmercial_directory_seller$assets_home_bottom_icons_user_active_svg = 'packages/commmercial_directory_seller/assets/home_bottom_icons/user_active.svg';

  static const String assets_icons_Stripe__company__Logo_wine_svg = 'assets/icons/Stripe_(company)-Logo.wine.svg';
  static const String commmercial_directory_seller$assets_icons_Stripe__company__Logo_wine_svg = 'packages/commmercial_directory_seller/assets/icons/Stripe_(company)-Logo.wine.svg';

  static const String assets_icons_X_png = 'assets/icons/X.png';
  static const String commmercial_directory_seller$assets_icons_X_png = 'packages/commmercial_directory_seller/assets/icons/X.png';

  static const String assets_icons_aggression_svg = 'assets/icons/aggression.svg';
  static const String commmercial_directory_seller$assets_icons_aggression_svg = 'packages/commmercial_directory_seller/assets/icons/aggression.svg';

  static const String assets_icons_apple_icon_svg = 'assets/icons/apple_icon.svg';
  static const String commmercial_directory_seller$assets_icons_apple_icon_svg = 'packages/commmercial_directory_seller/assets/icons/apple_icon.svg';

  static const String assets_icons_authentication_svg = 'assets/icons/authentication.svg';
  static const String commmercial_directory_seller$assets_icons_authentication_svg = 'packages/commmercial_directory_seller/assets/icons/authentication.svg';

  static const String assets_icons_awesome_share_svg = 'assets/icons/awesome-share.svg';
  static const String commmercial_directory_seller$assets_icons_awesome_share_svg = 'packages/commmercial_directory_seller/assets/icons/awesome-share.svg';

  static const String assets_icons_c_phone_svg = 'assets/icons/c_phone.svg';
  static const String commmercial_directory_seller$assets_icons_c_phone_svg = 'packages/commmercial_directory_seller/assets/icons/c_phone.svg';

  static const String assets_icons_edit_svg = 'assets/icons/edit.svg';
  static const String commmercial_directory_seller$assets_icons_edit_svg = 'packages/commmercial_directory_seller/assets/icons/edit.svg';

  static const String assets_icons_error_svg = 'assets/icons/error.svg';
  static const String commmercial_directory_seller$assets_icons_error_svg = 'packages/commmercial_directory_seller/assets/icons/error.svg';

  static const String assets_icons_exclamation_svg = 'assets/icons/exclamation.svg';
  static const String commmercial_directory_seller$assets_icons_exclamation_svg = 'packages/commmercial_directory_seller/assets/icons/exclamation.svg';

  static const String assets_icons_facebook_icon_svg = 'assets/icons/facebook_icon.svg';
  static const String commmercial_directory_seller$assets_icons_facebook_icon_svg = 'packages/commmercial_directory_seller/assets/icons/facebook_icon.svg';

  static const String assets_icons_fav_filled_svg = 'assets/icons/fav_filled.svg';
  static const String commmercial_directory_seller$assets_icons_fav_filled_svg = 'packages/commmercial_directory_seller/assets/icons/fav_filled.svg';

  static const String assets_icons_g_mode_svg = 'assets/icons/g_mode.svg';
  static const String commmercial_directory_seller$assets_icons_g_mode_svg = 'packages/commmercial_directory_seller/assets/icons/g_mode.svg';

  static const String assets_icons_google_icon_svg = 'assets/icons/google_icon.svg';
  static const String commmercial_directory_seller$assets_icons_google_icon_svg = 'packages/commmercial_directory_seller/assets/icons/google_icon.svg';

  static const String assets_icons_language_svg = 'assets/icons/language.svg';
  static const String commmercial_directory_seller$assets_icons_language_svg = 'packages/commmercial_directory_seller/assets/icons/language.svg';

  static const String assets_icons_network_error_svg = 'assets/icons/network_error.svg';
  static const String commmercial_directory_seller$assets_icons_network_error_svg = 'packages/commmercial_directory_seller/assets/icons/network_error.svg';

  static const String assets_icons_no_data_svg = 'assets/icons/no_data.svg';
  static const String commmercial_directory_seller$assets_icons_no_data_svg = 'packages/commmercial_directory_seller/assets/icons/no_data.svg';

  static const String assets_icons_payment_svg = 'assets/icons/payment.svg';
  static const String commmercial_directory_seller$assets_icons_payment_svg = 'packages/commmercial_directory_seller/assets/icons/payment.svg';

  static const String assets_icons_person_png = 'assets/icons/person.png';
  static const String commmercial_directory_seller$assets_icons_person_png = 'packages/commmercial_directory_seller/assets/icons/person.png';

  static const String assets_icons_saudi_arabia_png = 'assets/icons/saudi_arabia.png';
  static const String commmercial_directory_seller$assets_icons_saudi_arabia_png = 'packages/commmercial_directory_seller/assets/icons/saudi_arabia.png';

  static const String assets_icons_searching_svg = 'assets/icons/searching.svg';
  static const String commmercial_directory_seller$assets_icons_searching_svg = 'packages/commmercial_directory_seller/assets/icons/searching.svg';

  static const String assets_icons_share_svg = 'assets/icons/share.svg';
  static const String commmercial_directory_seller$assets_icons_share_svg = 'packages/commmercial_directory_seller/assets/icons/share.svg';

  static const String assets_icons_success_svg = 'assets/icons/success.svg';
  static const String commmercial_directory_seller$assets_icons_success_svg = 'packages/commmercial_directory_seller/assets/icons/success.svg';

  static const String assets_icons_usa_png = 'assets/icons/usa.png';
  static const String commmercial_directory_seller$assets_icons_usa_png = 'packages/commmercial_directory_seller/assets/icons/usa.png';

  static const String assets_icons_v_mode_svg = 'assets/icons/v_mode.svg';
  static const String commmercial_directory_seller$assets_icons_v_mode_svg = 'packages/commmercial_directory_seller/assets/icons/v_mode.svg';

  static const String assets_icons_verivication_png = 'assets/icons/verivication.png';
  static const String commmercial_directory_seller$assets_icons_verivication_png = 'packages/commmercial_directory_seller/assets/icons/verivication.png';

  static const String assets_notifications_increase_assets_svg = 'assets/notifications/increase_assets.svg';
  static const String commmercial_directory_seller$assets_notifications_increase_assets_svg = 'packages/commmercial_directory_seller/assets/notifications/increase_assets.svg';

  static const String assets_notifications_transaction_done_svg = 'assets/notifications/transaction_done.svg';
  static const String commmercial_directory_seller$assets_notifications_transaction_done_svg = 'packages/commmercial_directory_seller/assets/notifications/transaction_done.svg';

  static const String assets_notifications_transaction_failed_svg = 'assets/notifications/transaction_failed.svg';
  static const String commmercial_directory_seller$assets_notifications_transaction_failed_svg = 'packages/commmercial_directory_seller/assets/notifications/transaction_failed.svg';

  static const String assets_notifications_transaction_processed_svg = 'assets/notifications/transaction_processed.svg';
  static const String commmercial_directory_seller$assets_notifications_transaction_processed_svg = 'packages/commmercial_directory_seller/assets/notifications/transaction_processed.svg';

  static const String assets_onboarding_email_confirmation_svg = 'assets/onboarding/email_confirmation.svg';
  static const String commmercial_directory_seller$assets_onboarding_email_confirmation_svg = 'packages/commmercial_directory_seller/assets/onboarding/email_confirmation.svg';

  static const String assets_onboarding_onboarding_1_svg = 'assets/onboarding/onboarding_1.svg';
  static const String commmercial_directory_seller$assets_onboarding_onboarding_1_svg = 'packages/commmercial_directory_seller/assets/onboarding/onboarding_1.svg';

  static const String assets_onboarding_onboarding_2_svg = 'assets/onboarding/onboarding_2.svg';
  static const String commmercial_directory_seller$assets_onboarding_onboarding_2_svg = 'packages/commmercial_directory_seller/assets/onboarding/onboarding_2.svg';

  static const String assets_onboarding_onboarding_3_svg = 'assets/onboarding/onboarding_3.svg';
  static const String commmercial_directory_seller$assets_onboarding_onboarding_3_svg = 'packages/commmercial_directory_seller/assets/onboarding/onboarding_3.svg';

  static const String assets_splash_splash_screen_png = 'assets/splash/splash_screen.png';
  static const String commmercial_directory_seller$assets_splash_splash_screen_png = 'packages/commmercial_directory_seller/assets/splash/splash_screen.png';

  static const String assets_translations_ar_json = 'assets/translations/ar.json';
  static const String commmercial_directory_seller$assets_translations_ar_json = 'packages/commmercial_directory_seller/assets/translations/ar.json';

  static const String assets_translations_en_json = 'assets/translations/en.json';
  static const String commmercial_directory_seller$assets_translations_en_json = 'packages/commmercial_directory_seller/assets/translations/en.json';
}
